name: weather
description: weather app to study Flutter and Dart

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^7.0.1
  http: ^0.13.0
  flutter_spinkit: ^4.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true



  fonts:
  - family: Erased_Typewriter
    fonts:
    - asset: fonts/Erased_Typewriter.otf


